config/config-default/field.field.node.book.body.yml
config/config-default/field.field.node.book.field_attachments.yml
config/config-default/field.field.node.book.field_division.yml
config/config-default/field.field.node.book.field_links.yml
config/config-default/field.field.node.book.field_metatag.yml
config/config-default/field.field.node.book.field_subject_matter.yml
config/config-default/field.field.node.book.field_tags.yml
config/config-default/field.field.node.news.body.yml
config/config-default/field.field.node.news.field_attachments.yml
config/config-default/field.field.node.news.field_division.yml
config/config-default/field.field.node.news.field_links.yml
config/config-default/field.field.node.news.field_metatag.yml
config/config-default/field.field.node.news.field_news_type.yml
config/config-default/field.field.node.news.field_subject_matter.yml
config/config-default/field.field.node.news.field_tags.yml
config/config-default/field.field.node.person.body.yml
config/config-default/field.field.node.person.field_division.yml
config/config-default/field.field.node.person.field_first_name.yml
config/config-default/field.field.node.person.field_images.yml
config/config-default/field.field.node.person.field_last_name.yml
config/config-default/field.field.node.person.field_metatag.yml
config/config-default/field.field.node.person.field_person_type.yml
config/config-default/field.field.node.person.field_subject_matter.yml
config/config-default/field.field.node.person.field_tags.yml
config/config-default/field.storage.node.field_images.yml

Added descriptions to news, book, and person fields.

TC-50-53-55 News Book Person with Descriptions

---

config/config-default/field.field.node.book.field_division.yml
config/config-default/field.field.node.book.field_subject_matter.yml
config/config-default/field.field.node.book.field_tags.yml
config/config-default/field.field.node.news.field_division.yml
config/config-default/field.field.node.news.field_news_type.yml
config/config-default/field.field.node.news.field_subject_matter.yml
config/config-default/field.field.node.news.field_tags.yml
config/config-default/field.field.node.person.field_division.yml
config/config-default/field.field.node.person.field_images.yml
config/config-default/field.field.node.person.field_person_type.yml
config/config-default/field.field.node.person.field_subject_matter.yml
config/config-default/field.field.node.person.field_tags.yml

Add create entities for taxonomy terms that don't exist for news, book, and person.

TC-50-53-55 News Book Person Create Taxonomy Terms

---

config/config-default/core.entity_view_display.node.book.default.yml
config/config-default/core.entity_view_display.node.news.default.yml
config/config-default/core.entity_view_display.node.person.default.yml

Adjust display for news, book, and person content types.

TC-50-53-55 News Book Person Display Adjustments

---

config/config-default/core.entity_form_display.node.document.default.yml
config/config-default/field.field.node.document.body.yml

Second attempt to merge TC-158 with branch created off latest master

Feature/tc 158  document tweaks2

---

web/themes/custom/jcc_base/preprocess/block/block--views-block--events-block-1.preprocess.inc
web/themes/custom/jcc_base/preprocess/block/block--views-block--events-filterable-block-1.preprocess.inc
web/themes/custom/jcc_base/preprocess/block/block--views-block--news-block-1.preprocess.inc
web/themes/custom/jcc_base/preprocess/block/block--views-block--news-filterable-block-1.preprocess.inc

Minor fixes to news and event blocks to coincide with component style updates in courtyard.

TC-272--News-Block-Fixes

---

web/modules/custom/jcc_book_navigation/templates/jcc-book-navigation-block.html.twig
web/themes/custom/jcc_base/templates/_patterns/02-molecules/navigation/side-nav/_side-nav.scss

TC-247: adding chevrons to parent links if child pages exist

---

composer.lock
web/themes/custom/jcc_base/src/js/jcc_base.script.js
web/themes/custom/jcc_base/templates/node/node--announcement.html.twig
web/themes/custom/jcc_base/templates/page/page--node--book.html.twig
web/themes/custom/jcc_base/templates/page/page--search.html.twig
web/themes/custom/jcc_base/templates/page/page.html.twig
web/themes/custom/jcc_newsroom/templates/page/page--front.html.twig

Mainly reposition alert under main region for visibility and reverted fixes in pattern lib. Also, disabling smooth scroll JS for the time being because it's disrupting functional tabbing and jump anchor behaviors.

WSGEN-1198: updated pattern lib & moved alert under main region

---

web/themes/custom/jcc_components/templates/field/field--paragraph--body.html.twig

Remove default div wrapper from body paragraph so required css is used.

Fix body paragraph field wrapper

---

composer.lock
web/themes/custom/jcc_components/templates/form/fieldset.html.twig
web/themes/custom/jcc_components/templates/form/form-element.html.twig
web/themes/custom/jcc_components/templates/form/select.html.twig
web/themes/custom/jcc_components/templates/paragraph/paragraph--webform.html.twig

From https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/2001

TCI-465 webforms enhancements

---

config/config-inyo/core.extension.yml
config/config-inyo/rest.settings.yml
config/config-inyo/serialization.settings.yml
config/config-inyo/views.view.export_feedback.yml

Used core modules: rest, basic_auth, views, instead of additonal contribs like webform_rest.

TCI-627: Add rest export for feedback form submissions based on sid.

---

composer.lock

TCI-866 :: Footer Update

---

composer.json
composer.lock
patches/get-entity-class-null-error-1.patch

[TCI-883] Fix core issue causing content importer to break after Drupal 9 upgrade.
[TCI-883]: https://judasdg.atlassian.net/browse/TCI-883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TCI-883] Fix core issue causing content importer to break after Drupal 9 upgrade.

---

web/modules/custom/xlsx/src/Controller/XlsxListBuilder.php
web/modules/custom/xlsx/src/CronImports.php
web/modules/custom/xlsx/src/Entity/XlsxEntity.php

[TCI-930] - Fixes issue with cron imports.

[TCI-930] Fix cron status on the content importer listing page.

---

web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/editor.editor.minimal.yml
web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/editor.editor.snippet.yml

Hi @baptisten 
Updated same code for snippet and minimul. Please review.

Added editor formatting buttons to snippet and minimul

---

config/config-inyo/editor.editor.body.yml
config/config-inyo/editor.editor.minimal.yml
web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/editor.editor.body.yml
web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/editor.editor.minimal.yml

Hi @baptisten Changed some control positions and removed extra controls from "Lead" text editor. Please approve.

Feature/tci 984  editor control request

---

web/themes/custom/jcc_components/jcc_components.info.yml
web/themes/custom/jcc_components/jcc_components.libraries.yml
web/themes/custom/jcc_components/src/css/print.css

Added print css for trialcourt.

TCI-922--Added print css in trialcourt

---

composer.lock
config/config-inyo/editor.editor.aside.yml
config/config-inyo/filter.format.aside.yml
web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/editor.editor.aside.yml
web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/filter.format.aside.yml

Composer.lock file generated and Formats added into aside editor.

Feature/tci 691  h4 css added aside editor

---

web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/core.entity_form_display.paragraph.card.default.yml
web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/field.field.node.subpage.field_components.yml

Added layout section option to subpage component field and set card media field to media library option.

[fix] -- Added layout section option to subpage component field.

---

composer.json
config/config-sanmateo/media.settings.yml
patches/3151977-d9-media-recursive-rendering.patch

Here is the patch link https://www.drupal.org/files/issues/2021-09-24/3151977-d9-media-recursive-rendering.patch

Adding patch for core/media module to render more than 20 images

---

web/themes/custom/jcc_elevated/includes/media.inc
web/themes/custom/jcc_elevated/templates/media/media--publication.html.twig

[DCAS-223]
Address php error on publication media items. Checks if the entity has the field first before checking for a value.

[DCAS-223] -- Address php error on publication media items.

---

web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/core.entity_view_display.media.remote_video.container_100_percent.yml
web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/core.entity_view_display.media.remote_video.container_25_percent.yml
web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/core.entity_view_display.media.remote_video.container_50_percent.yml
web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/core.entity_view_display.media.remote_video.container_75_percent.yml
web/themes/custom/jcc_components/includes/media.inc
web/themes/custom/jcc_components/src/css/image-styles.css
web/themes/custom/jcc_components/templates/media/media--remote-video.html.twig

Updated code in trial court for edit button fix.
The fixed includes:
1. Create display mode for remote video in web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config.
2. Updated media--remote-video.html.twig
3. updated includes/media/media.inc

Fixes the edit media button for video.

---

config/config-inyo/nodeaccess.settings.yml
config/config-inyo/pathauto.pattern.request_rfp_content_type_pattern.yml
web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/nodeaccess.settings.yml
web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/pathauto.pattern.request_rfp_content_type_pattern.yml
web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/views.view.content.yml

[DCAS-261]
Permission update for Request content type and fix to pathauto pattern

[DCAS-261] -- Permission update for Request content type and fix to pathauto pattern

---

config/config-santaclara/core.entity_form_display.node.location.default.yml
config/config-santaclara/core.entity_view_display.node.location.default.yml

Added yml for form and node display for locations page.

Added form display and node display

---

web/themes/custom/jcc_components/includes/location-details.inc

Implemented drupal coding standard and added logic for missing link.

Added the missing url link for service name and formatted code

---

web/profiles/jcc_components_profile/modules/custom/jcc_tc2_all_immutable_config/config/install/field.storage.paragraph.field_service_phone_number.yml
web/themes/custom/jcc_components/includes/location-details.inc
web/themes/custom/jcc_components/includes/node.inc
web/themes/custom/jcc_components/src/css/location-page.css

Changed Cardinality of phone number to one.
Refactored code.
Phone number field for service is linkable and re added.

Feature/tci 1218 location page sections  deployment

---

composer.lock
web/modules/custom/jcc_elevated_custom/css/jcc-elevated-custom.css
web/themes/custom/jcc_elevated/includes/paragraph.inc
web/themes/custom/jcc_elevated/templates/views/views-view--justices-appellate-legacy-project--all-justices.html.twig
web/themes/custom/jcc_elevated/templates/views/views-view--justices-judges--current.html.twig

Includes:
Storybook update
Justices views template inline padding fix
Adjust Cards text variable to be null if truly empty so that an empty div doesn't print out.
Temp css fixes

[COURTS-210-211] -- Style/Template fixes and Storybook update
